# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='last name')),
                ('nickname', models.CharField(blank=True, max_length=255, verbose_name='nickname')),
                ('description', models.TextField(blank=True, max_length=10000, verbose_name='description')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
            ],
            options={
                'ordering': ['nickname', 'last_name', 'first_name'],
                'verbose_name': 'person',
                'verbose_name_plural': 'people',
            },
        ),
    ]
