# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20160913_0522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='face',
        ),
        migrations.AddField(
            model_name='face',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='people.Person'),
        ),
    ]
