# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20160913_0540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='people.Person')),
                ('head', models.CharField(blank=True, max_length=255, verbose_name='head')),
                ('body', models.CharField(blank=True, max_length=255, verbose_name='body')),
                ('belt', models.CharField(blank=True, max_length=255, verbose_name='belt')),
                ('legs', models.CharField(blank=True, max_length=255, verbose_name='legs')),
                ('feet', models.CharField(blank=True, max_length=255, verbose_name='feet')),
            ],
        ),
    ]
