# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_cloth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=255, verbose_name='color')),
                ('length', models.CharField(blank=True, max_length=255, verbose_name='length')),
                ('hairdress', models.CharField(blank=True, max_length=255, verbose_name='hairdress')),
                ('parting', models.CharField(blank=True, max_length=255, verbose_name='hairdress')),
                ('curling', models.CharField(blank=True, max_length=255, verbose_name='hairdress')),
            ],
        ),
        migrations.RemoveField(
            model_name='face',
            name='hair',
        ),
        migrations.AlterField(
            model_name='cloth',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Person'),
        ),
        migrations.AlterField(
            model_name='face',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Person'),
        ),
        migrations.AddField(
            model_name='hair',
            name='face',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Face'),
        ),
    ]
