# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20160913_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hair',
            name='face',
        ),
        migrations.AddField(
            model_name='hair',
            name='person',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='people.Person'),
        ),
    ]
