# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0002_auto_20160807_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='newspaper',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='year',
        ),
        migrations.AddField(
            model_name='newspaper',
            name='issues',
            field=models.ManyToManyField(to='newspaper.Issue'),
        ),
        migrations.AddField(
            model_name='year',
            name='issues',
            field=models.ManyToManyField(to='newspaper.Issue'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue',
            field=models.IntegerField(default=0),
        ),
    ]
