# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0003_auto_20160903_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspaper',
            name='issues',
        ),
        migrations.RemoveField(
            model_name='year',
            name='issues',
        ),
        migrations.AddField(
            model_name='issue',
            name='newspaper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newspaper.Newspaper'),
        ),
        migrations.AddField(
            model_name='issue',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newspaper.Year'),
        ),
    ]
