# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0005_auto_20160904_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='description',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
