# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0006_auto_20160905_0324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['newspaper', 'year', 'issue'], 'verbose_name': 'issue', 'verbose_name_plural': 'issues'},
        ),
        migrations.AlterModelOptions(
            name='newspaper',
            options={'ordering': ['title'], 'verbose_name': 'newspaper', 'verbose_name_plural': 'newspapers'},
        ),
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ['year'], 'verbose_name': 'year', 'verbose_name_plural': 'years'},
        ),
        migrations.AlterField(
            model_name='issue',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue',
            field=models.IntegerField(default=0, verbose_name='issue'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='newspaper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newspaper.Newspaper', verbose_name='newspaper'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newspaper.Year', verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='description',
            field=models.TextField(blank=True, max_length=10000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.IntegerField(verbose_name='year'),
        ),
    ]
