# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
                ('description', models.TextField(blank=True, max_length=10000, verbose_name='description')),
            ],
            options={
                'verbose_name': 'world',
                'ordering': ['title'],
                'verbose_name_plural': 'worlds',
            },
        ),
    ]
