# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 17:19
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='world',
            name='description',
        ),
        migrations.AddField(
            model_name='world',
            name='rating',
            field=models.PositiveIntegerField(default=80, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='world',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/web/worlds/__attach/', location='../media/worlds/__attach/'), upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='world',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='world',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
