# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_auto_20160919_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='world',
            options={'ordering': ['-rating', 'title'], 'verbose_name': 'world', 'verbose_name_plural': 'worlds'},
        ),
        migrations.AlterField(
            model_name='world',
            name='rating',
            field=models.PositiveIntegerField(default=0, verbose_name='Rating'),
        ),
    ]
