# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 09:32
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0012_auto_20160913_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('folder', models.CharField(max_length=255, verbose_name='Folder')),
                ('image', models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, location=None), upload_to='', verbose_name='Image')),
                ('description', models.TextField(max_length=10000, verbose_name='Description')),
                ('authors', models.ManyToManyField(blank=True, to='people.Person', verbose_name='Authors')),
            ],
        ),
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('folder', models.CharField(max_length=255, verbose_name='Folder')),
                ('image', models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, location=None), upload_to='', verbose_name='Image')),
                ('description', models.TextField(max_length=10000, verbose_name='Description')),
                ('parent', models.ManyToManyField(blank=True, related_name='_bookgenre_parent_+', to='book.BookGenre', verbose_name='Parent genre')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='book.BookGenre', verbose_name='Genres'),
        ),
    ]
