# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 08:52
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20160924_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookgenre',
            name='image',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url='/web/genres/__attach/', location='../media/genres/__attach/'), upload_to='', verbose_name='Image'),
        ),
    ]
