# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20161110_0852'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='ScienceBook',
        ),
    ]
