# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('date', models.DateField(verbose_name='date')),
                ('description', models.TextField(max_length=10000, verbose_name='description')),
            ],
            options={
                'verbose_name': 'news',
                'ordering': ['date'],
                'verbose_name_plural': 'news',
            },
        ),
    ]
