# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='brief',
            field=models.TextField(default='', max_length=512, verbose_name='brief'),
            preserve_default=False,
        ),
    ]
