# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-18 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGameGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, max_length=10000, verbose_name='description')),
            ],
            options={
                'verbose_name_plural': 'video game genres',
                'verbose_name': 'video game genre',
            },
        ),
        migrations.AddField(
            model_name='videogame',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='games.VideoGameGenre', verbose_name='genre'),
            preserve_default=False,
        ),
    ]
