# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20161018_1114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['title'], 'verbose_name': 'game', 'verbose_name_plural': 'games'},
        ),
        migrations.AlterModelOptions(
            name='videogamegenre',
            options={'ordering': ['title'], 'verbose_name': 'video game genre', 'verbose_name_plural': 'video game genres'},
        ),
    ]
