# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20160904_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=10000)),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['issue', 'page', 'title']},
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='article.ArticleType'),
            preserve_default=False,
        ),
    ]
