# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20160905_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='linked',
            field=models.ManyToManyField(to='article.Article'),
        ),
    ]
