# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_article_linked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='linked',
            field=models.ManyToManyField(blank=True, null=True, to='article.Article'),
        ),
    ]
