# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20160905_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='articles',
        ),
        migrations.RemoveField(
            model_name='note',
            name='note_type',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='NoteType',
        ),
    ]
