# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20160905_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['issue', 'page', 'title'], 'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='articletype',
            options={'verbose_name': 'article type', 'verbose_name_plural': 'article_types'},
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleType', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.ArticleCategory', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newspaper.Issue', verbose_name='issue'),
        ),
        migrations.AlterField(
            model_name='article',
            name='linked',
            field=models.ManyToManyField(blank=True, related_name='_article_linked_+', to='article.Article', verbose_name='linked articles'),
        ),
        migrations.AlterField(
            model_name='article',
            name='page',
            field=models.IntegerField(default=1, verbose_name='page'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='description',
            field=models.TextField(max_length=10000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='newspaper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newspaper.Newspaper', verbose_name='newspaper'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='description',
            field=models.TextField(max_length=10000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
    ]
