# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0011_auto_20160912_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('page', models.IntegerField(default=1, verbose_name='page')),
                ('article_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleType', verbose_name='type')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.ArticleCategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'article template',
                'ordering': ['category__title', 'page', 'title'],
                'verbose_name_plural': 'article templates',
            },
        ),
    ]
