# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletemplate',
            options={'ordering': ['page', 'category__title'], 'verbose_name': 'article template', 'verbose_name_plural': 'article templates'},
        ),
        migrations.RemoveField(
            model_name='articletemplate',
            name='title',
        ),
    ]
